kind = "api"
previewPath = "/"
title = "Phosphene Simulator"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "Phosphene Simulator"
paths = ["/"]

[services.development]
run = "sleep infinity"
