kind = "api"
previewPath = "/"
title = "Phosphene Simulator"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8001
name = "Phosphene Simulator"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace/artifacts/phosphene-sim && uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
